### ISSUE TITLE
Allow passing secrets via environment variable

### ISSUE THREAD

**Issue by MMore** [zerok/jiravars#8]
Sensitive information like `login` and `password` should be kept aside from the usual application config so that we can increase security. Passing such information as env variable became best practice. Let's use that approach. What do you think?

**Comment by matey-jack** [comment]
we're successfully using that in production since more than a year now, so I guess we can close the issue as "done" :rocket:

**Comment by MMore** [comment]
Indeed, thanks @matey-jack. Greetings 👋  ~Mathias

**Comment by zerok** [comment]
Awesome :D Thank you for testing this!
